name: Workflow
on: workflow_dispatch
jobs:
  basic_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello"
        
      - name: Something
        run: echo "World"
